### ISSUE TITLE
Regarding small panels

### ISSUE THREAD

**Issue by vipuljain222** [gedoardo83/GARFIELD-NGS#2]
Hi,
will it good to process tissue exomes (TVC Somatic parameter) with this tool? and
How can I use this tool for small panels like AmpliSeq CHP, CCP? 

Thanks

**Comment by gedoardo83** [comment]
Hi, we have not tested the tool with somatic calls and I can't recommend its use in this field, since somatic calls are quite different from germline ones in variants features, especially alternate allele observation. We have tried the tool on data generated from custom gene panels (around 30 genes) and it performs well. Even if we do not performed extensive validation on small panels, I suppose that our approach would extend also to this approach. Indeed coverage based features (that should have very different distributions in gene panels compared to exomes) have a small weight in our models. So I think that as long as you stay with germline calls and have a canonical VCF input, GARFIELD-NGS could be useful for your analysis.

**Comment by vipuljain222** [comment]
Thanks for the response. I have tested the tool on small panels but score for all the variants are above 1 (in the range of 100 to 900).

**Comment by gedoardo83** [comment]
Values above one are not possible...the algorithm compute probability values between 0 and 1. Probably there are some issues in managing your data and formatting the output.Can you email me a piece of your VCF file so I can try to figure out what's going on?Inviato dal mio dispositivo Huawei-------- Messaggio originale --------Oggetto: Re: [gedoardo83/GARFIELD-NGS] Regarding small panels (#2)Da: vipuljain222 A: gedoardo83/GARFIELD-NGS CC: gedoardo83 ,Comment Thanks for the response. I have tested the tool on small panels but score for all the variants are above 1 (in the range of 100 to 900).

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gedoardo83/GARFIELD-NGS","title":"gedoardo83/GARFIELD-NGS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gedoardo83/GARFIELD-NGS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vipuljain222 in #2: Thanks for the response. I have tested the tool on small panels but score for all the variants are above 1 (in the range of 100 to 900). \r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/gedoardo83/GARFIELD-NGS/issues/2#issuecomment-384155776"}}}

Informativa sulla Privacy: http://www.unibs.it/node/8155

**Comment by vipuljain222** [comment]
PFA

Thanks & Regards,

Vipul Todarwal

Bioinformatician,
Datar Cancer Genetics Limited,
Nashik.
Mob.- 9822434003

**Comment by vipuljain222** [comment]
PFA
[test_sample.txt](https://github.com/gedoardo83/GARFIELD-NGS/files/1946166/test_sample.txt)

**Comment by gedoardo83** [comment]
Your problem is due to erroneous processing of missing features values, that can be reported as "." in VCf INFO column. I've fixed this bug and updated Predict.pl.
In your case, please note that GARFIELD-VCF provides useful predictions only or variant positions, but not for position where there are no alternate alleles observed (those reported as 0/0 genotype). The algorithm relies on information from alternate allele distribution to perform prediction and since there are no alternate alleles in 0/0 variants, it would result in abnormal predictions. GARFIELD-NGS scores remains informative for other variants (0/1 and 1/1 genotypes).

**Comment by vipuljain222** [comment]
Thanks. Now its working fine.

**Comment by gedoardo83** [comment]
Great!
